# Generated by Django 4.2.7 on 2023-11-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pawn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("birthday", models.DateField(null=True)),
                ("iq", models.FloatField(default=0.0, null=True)),
                ("positioning", models.FloatField(default=0.0, null=True)),
                ("shooting", models.FloatField(default=0.0, null=True)),
                ("passing", models.FloatField(default=0.0, null=True)),
                ("goaltending", models.FloatField(default=0.0, null=True)),
                ("skating", models.FloatField(default=0.0, null=True)),
                ("checking", models.FloatField(default=0.0, null=True)),
                ("balancing", models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PawnBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.FloatField(default=1.0)),
                ("torso", models.FloatField(default=1.0)),
                ("arm_right", models.FloatField(default=1.0)),
                ("arm_left", models.FloatField(default=1.0)),
                ("leg_right", models.FloatField(default=1.0)),
                ("leg_left", models.FloatField(default=1.0)),
                (
                    "pawn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pawn.pawn"
                    ),
                ),
            ],
        ),
    ]
