---
version: '2.4'

volumes:
  postgres_data:


services:
  api:
    build:
      context: .
      dockerfile: compose/Dockerfile
    working_dir: /hoki/api
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@info.com
    volumes:
      - .:/hoki
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
